[package]
name = "webhook"
version = "0.1.0"
authors = ["Aatu Hieta <aatu@hieta.fi>"]

[dependencies]
telegram = { path = "telegram/src/" }
redis = "0.8"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"